#spring:
#  ### Datasource
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3606/modongmun?serverTimezone=Asia/Seoul
#    username: ssafy
#    password: 1234
spring:
  ### Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modongmun?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

  ### JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl_auto: update